# Generated by Django 5.0.1 on 2024-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.SmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('circuit_description', models.CharField(max_length=100)),
                ('circuit_status', models.BooleanField(default=True)),
                ('num_cycles', models.SmallIntegerField(default=1)),
                ('num_events', models.SmallIntegerField(default=1)),
                ('event_duration', models.SmallIntegerField(default=5)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_random', models.BooleanField(default=False)),
            ],
        ),
    ]
