# Generated by Django 5.0.1 on 2024-02-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cycle', models.SmallIntegerField(default=1)),
                ('event', models.SmallIntegerField(default=1)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_duration', models.SmallIntegerField(default=5)),
                ('circuit_slug', models.CharField(blank=True, max_length=20)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuits.circuit')),
            ],
        ),
    ]
